#!/usr/bin/env bash
#
# Generates the production release keystore for Shield and writes keystore.properties.
#
# Creates a 4096-bit RSA release key using keytool and records the connection
# details in keystore.properties (git-ignored). The script is idempotent: if a
# keystore already exists it is NEVER regenerated, because rotating the upload
# key makes an already-published app impossible to update.
#
# Passwords are taken from the environment when present, otherwise generated
# from the system CSPRNG:
#   SHIELD_KEYSTORE_PASSWORD   - keystore/store password
#   SHIELD_KEY_PASSWORD        - key password (defaults to the store password)
#
# Usage:
#   ./scripts/generate-keystore.sh
#   ./scripts/generate-keystore.sh --alias shield-release --validity 10950
#
# Options:
#   --alias <name>       Key alias. Default: shield-release
#   --validity <days>    Certificate validity. Default: 10000 (~27 years).
#                        Google Play requires the upload key to stay valid past
#                        22 October 2033.
#   --dname <name>       Certificate distinguished name.
#   --keystore <path>    Destination. Default: <repo>/release-keys/shield-release.p12

set -euo pipefail

ALIAS="shield-release"
VALIDITY=10000
DNAME="CN=Shield, OU=Mobile, O=Gamblock, L=Bengaluru, ST=Karnataka, C=IN"
KEYSTORE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --alias)    ALIAS="$2"; shift 2 ;;
    --validity) VALIDITY="$2"; shift 2 ;;
    --dname)    DNAME="$2"; shift 2 ;;
    --keystore) KEYSTORE="$2"; shift 2 ;;
    -h|--help)  sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -n "$KEYSTORE" ] || KEYSTORE="$REPO_ROOT/release-keys/shield-release.p12"
PROPERTIES="$REPO_ROOT/keystore.properties"

step()  { printf '==> %s\n' "$1"; }
ok()    { printf '    %s\n' "$1"; }
warn()  { printf '    %s\n' "$1" >&2; }
die()   { printf '    %s\n' "$1" >&2; exit 1; }

step "Shield release keystore setup"

if [ -e "$KEYSTORE" ]; then
  warn "Keystore already exists: $KEYSTORE"
  die  "Refusing to overwrite. Replacing the upload key would break updates"
  die  "for any version already published to Google Play."
  ok   "Delete the file yourself only if you are certain it is unused."
  [ -f "$PROPERTIES" ] || die "keystore.properties is missing, so the build cannot sign with this key."
  exit 1
fi

if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/keytool" ]; then
  KEYTOOL="$JAVA_HOME/bin/keytool"
elif command -v keytool >/dev/null 2>&1; then
  KEYTOOL="$(command -v keytool)"
else
  die "keytool not found. Install a JDK 17+ and set JAVA_HOME, or put keytool on PATH."
fi
ok "keytool: $KEYTOOL"

gen_password() {
  # `|| true` keeps `set -o pipefail` from tripping over the SIGPIPE that
  # head(1) sends to tr when it stops reading /dev/urandom.
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom 2>/dev/null | head -c "${1:-28}" || true
}

STORE_PASS="${SHIELD_KEYSTORE_PASSWORD:-$(gen_password 28)}"
KEY_PASS="${SHIELD_KEY_PASSWORD:-$STORE_PASS}"
[ "${#STORE_PASS}" -ge 6 ] || die "Store password must be at least 6 characters."
[ "${#KEY_PASS}"  -ge 6 ] || die "Key password must be at least 6 characters."
[ "$VALIDITY" -ge 365 ] 2>/dev/null || die "Validity must be at least 365 (got $VALIDITY)."

mkdir -p "$(dirname "$KEYSTORE")"
ok "created $(dirname "$KEYSTORE")"

step "Generating 4096-bit RSA key pair"
ok "alias=$ALIAS validity=${VALIDITY}d storetype=PKCS12"

# PKCS12 derives the key password from the store password, so they must match.
"$KEYTOOL" -genkeypair \
  -keystore "$KEYSTORE" \
  -storetype PKCS12 \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 4096 \
  -sigalg SHA256withRSA \
  -validity "$VALIDITY" \
  -dname "$DNAME" \
  -storepass "$STORE_PASS" \
  -keypass "$KEY_PASS" \
  >/dev/null 2>&1 || die "keytool failed. The keystore may be partially written; delete '$KEYSTORE' and retry."
ok "wrote $KEYSTORE"

step "Verifying the key"
"$KEYTOOL" -list -v -keystore "$KEYSTORE" -alias "$ALIAS" -storepass "$STORE_PASS" >/dev/null 2>&1 \
  || die "Verification failed; '$KEYSTORE' is not usable."
ok "key verifies successfully"

step "Writing keystore.properties"
REL_STORE="${KEYSTORE#"$REPO_ROOT"/}"
umask 077
cat > "$PROPERTIES" <<EOF
# Shield release signing. Generated by scripts/generate-keystore.sh.
# Never commit this file - it is covered by .gitignore.
storeFile=$REL_STORE
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$KEY_PASS
EOF
chmod 600 "$PROPERTIES"
ok "wrote $PROPERTIES"

printf '\n'
printf 'Next steps:\n'
printf "  1. Back up '%s' and keystore.properties somewhere you will\n" "$KEYSTORE"
printf '     NOT lose them. Losing the upload key means the published app can\n'
printf '     never be updated again.\n'
printf '  2. Play Console > App integrity > App signing: upload this key and\n'
printf '     enrol it in Play App Signing.\n'
printf '  3. ./gradlew bundleRelease   (keystore.properties is picked up automatically)\n'
printf '\n'
warn "Passwords are shown once. Store them in a password manager now."
printf '\n'
printf '    storePassword=%s\n' "$STORE_PASS" >&2
printf '    keyPassword=%s\n' "$KEY_PASS" >&2
